config/routes.rb
Iwilltravel::Application.routes.draw do
  get "about/index"

  root :to => "trips#index"
  
  get "start/index"
  post "start/location"
  post "start/from"
  post "start/to"

  get "start/enter"
  post "start/save"
  
  resources :trips

  get "details/plan"

  get "details/weather"

  get "details/clothes"

  get "details/pictures"
  post "details/add_item"
  get "details/edit_item"
  get "details/remove_item"

  get "home/index"
  get "home/add_section"
  get "home/settings"
  get "home/suggestions"

end

app/models/auto_suggester.rb
class AutoSuggester

  def initial_suggestions trip
    add_items trip, 1,
      [ "Book flight", "Book hotel", "Exchange money", "Print map" ]
    add_items trip, 2,
      [ "Sun screen", "Umbrella" ]
    add_items trip, 3,
      [ "2 pair of socks", "2 underwear", "2 T-shirts", "1 Jeans",
        "1 Jacket", "1 Hat", "1 Sweater" ]
    add_items trip, 4,
      [ "Book ticket for big wheel" ]
    trip.save!
  end

  def add_items trip, category, items
    items.each do |item|
      add_item trip, category, item
    end
  end
  
  def add_item trip, category, title
    item = Item.new
    item.category = category
    item.text = title
    item.suggested = true
    item.done = false
    
    trip.items << item
  end
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :done, :integer, :integer, :suggested, :text

  belongs_to :trip
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :items, :dependent => :destroy
  
  def complete?
    location && from && to
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  before_filter :find_trip
  
  def plan
    @items = Item.where( :trip_id  => @trip.id).where( :category => 1 )
    @category = 1
  end

  def weather
    @items = Item.where( :trip_id  => @trip.id).where( :category => 2 )
    @category = 2
  end

  def clothes
    @items = Item.where( :trip_id  => @trip.id).where( :category => 3 )
    @category = 3
  end

  def pictures
    @items = Item.where( :trip_id  => @trip.id).where( :category => 4 )
    @category = 4
  end

  def add_item
    category = params[:category]
    
    trip = Trip.find params[:id]
    
    item = Item.new
    item.text = params[:item_title]
    item.suggested = false
    item.done = false
    item.category = category
    
    item.save!
    trip.items << item
    trip.save!

    redirect_to_category trip, category
  end

  def edit_item
    render "add_item"
  end

  def remove_item
    item = Item.find params[:item_id]
    notice = "Deleted '#{item.text}'"
    Item.destroy params[:item_id]

    flash[:notice] = notice
    
    redirect_to_category @trip, params[:category]
  end

  private
  
  def find_trip
    @trip = Trip.find params[:id]
  end

  def redirect_to_category trip, category
    if category == "1"
      redirect_to :action => "plan", :id => trip.id
    elsif category == "2"
      redirect_to :action => "weather", :id => trip.id
    elsif category == "3"
      redirect_to :action => "clothes", :id => trip.id
    else
      redirect_to :action => "pictures", :id => trip.id
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @trip = Trip.find params[:id]

    @items1 = Item.where( :trip_id  => @trip.id).where( :category => 1 )
    @items2 = Item.where( :trip_id  => @trip.id).where( :category => 2 )
    @items3 = Item.where( :trip_id  => @trip.id).where( :category => 3 )
    @items4 = Item.where( :trip_id  => @trip.id).where( :category => 4 )
  end
  
  def settings
    render :layout => "application"
  end

  def suggestions
    if params[:id]
      @trip_id = params[:id]
    end
    render :layout => "application"
  end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
    @trip = Trip.new
    @trip.save!
  end

  def location
    @trip = Trip.find params[:id]
    @trip.location = params[:location]
    @trip.save!
  end
  
  def from
    @trip = Trip.find params[:id]
    @trip.from = params[:from]
    @trip.save!
  end
  
  def to
    @trip = Trip.find params[:id]
    @trip.to = params[:to]
    @trip.save!
    
    AutoSuggester.new.initial_suggestions @trip
  end

  def enter
    @trip = Trip.new
    @trip.save!
  end
  
  def save
    @trip = Trip.find params[:id]
    @trip.location = params[:location]
    @trip.from = params[:from]
    @trip.to = params[:to]
    @trip.save!
    
    AutoSuggester.new.initial_suggestions @trip

    redirect_to :controller => "home", :action => "index", :id => @trip.id
  end
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all.reject { |t| !t.complete? }.sort_by &:from

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, :notice => 'Trip was successfully created.' }
        format.json { render :json => @trip, :status => :created, :location => @trip }
      else
        format.html { render :action => "new" }
        format.json { render :json => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, :notice => 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
  
  def details_status items
    if items
      "0/#{items.count} done"
    else
      "undefined"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/trips_helper.rb
module TripsHelper

  def trip_date_range trip
    f = trip.from
    t = trip.to
    out = f.strftime( "%B #{f.day.ordinalize}" )
    if f.year != t.year
      out += " 2012"
    end
    out += " -"
    if f.year != t.year || f.month != t.month
      out += t.strftime(" %B")
    end
    out += t.strftime( " #{t.day.ordinalize} %Y" )
  end
  
  def trip_date d
    if d.year == Date.today.year
      out = d.strftime( "%A, %B #{d.day.ordinalize}" )
    else
      out = d.strftime( "%A, %B #{d.day.ordinalize} %Y" )
    end
  end
  
  def trip_short_date d
    if d.year == Date.today.year
      out = d.strftime( "%B #{d.day.ordinalize}" )
    else
      out = d.strftime( "%B #{d.day.ordinalize} %Y" )
    end
  end
  
  def trip_duration trip
    distance_of_time_in_words(trip.from, trip.to + 1.days)
  end
  
  def trip_title trip
    if trip.valid?
      "#{trip.location}, #{trip_date_range(trip)}, " +
      trip_duration( trip )
    else
      "Invalid trip data"
    end
  end

end

app/views/about/index.html.haml
%h2 Attributions

%ul
  %li
    Maps ©
    =link_to "OpenStreetMap", "http://www.openstreetmap.org"
    contributors,
    = link_to "CC BY-SA", "http://creativecommons.org/licenses/by-sa/2.0/"
  %li
    = link_to "Weather icons", "http://bharathp666.deviantart.com/art/Android-Weather-Icons-180719113"
  %li
    = link_to "MK Media Productions Clothes. by @yakobusan Jakob Montrasio, on Flickr", "http://www.flickr.com/photos/yakobusan/3252980056/"
    ,
    = link_to "CC BY-SA", "http://creativecommons.org/licenses/by-sa/2.0/"
  %li
    = link_to "London Eye by jimmyharris, on Flickr", "http://www.flickr.com/photos/jimmyharris/2523480499/"
    ,
    = link_to "CC BY-SA", "http://creativecommons.org/licenses/by-sa/2.0/"
  %li
    = link_to "London by Metro Centric, on Flickr", "http://www.flickr.com/photos/16782093@N03/3808446391/"
    ,
    = link_to "CC BY-SA", "http://creativecommons.org/licenses/by-sa/2.0/"
  %li
    = link_to "London England by az1172, on Flickr", "http://www.flickr.com/photos/az1172/2268286093/"
    ,
    = link_to "CC BY-SA", "http://creativecommons.org/licenses/by-sa/2.0/"

app/views/details/_clothes-overview.html.haml
%h2 Clothes
.section-content
  = image_tag "/images/clothes_dummy.png", :size => "200x370", :class => "center"
.status
  %span.status-text
    = details_status items
  %span.status-icon
    = image_tag "/images/checkmark-green.png"

app/views/details/_items.html.haml
.overview-link
  = link_to "Back to overview", :controller => "home", :id => @trip.id
.items
  - if flash[:notice]
    .flash
      = flash[:notice]
      &nbsp;
      = link_to "Undo", "#"
  - @items.each do |item|
    .item
      %p
        %span.check-box
          = check_box_tag "item#{item.id}"
          = label_tag "item#{item.id}", item.text
        - if item.suggested          
          %span.suggested-icon
            = link_to image_tag("/images/suggested-icon.png"),
              :controller => "home", :action => "suggestions", :id => @trip.id
        %span.actions
          = link_to "Edit", :action => "edit_item", :id => @trip.id
          = link_to "Remove", :action => "remove_item", :id => @trip.id,
            :item_id => item.id, :category => @category
  .item_editor
    %p
      = form_tag :action => "add_item" do |form|
        = text_field_tag :item_title
        &nbsp;
        = hidden_field_tag :id, @trip.id
        = hidden_field_tag :category, @category
        = submit_tag "Save"

  .item_adder
    = link_to "+ Add item", "#"

:javascript
  $(".item_adder").click(function () {
    $(".item_editor").toggle();
  });

  $(document).ready(function() {
    $(".check-box").click(function() {
      var count = $("[type='checkbox']:checked").length;
      var total = $("[type='checkbox']").length;
      $(".status-text").html(count + "/" + total + " done");
      if ( count === total ) {
        $(".status-icon").show();
      } else {
        $(".status-icon").hide();
      }
    });
  });

app/views/details/_pictures-overview.html.haml
- if controller.class.to_s == "HomeController"
  %span.adder
    %h2= link_to "+", :controller => "home", :action => "add_section"
%h2 Activities
.section-content
  = image_tag "/images/pictures_dummy.png", :size => "200x370", :class => "center"
.status
  %span.status-text
    = details_status items
  %span.status-icon
    = image_tag "/images/checkmark-green.png"

app/views/details/_plan-overview.html.haml
%h2 Plan
.section-content
  = image_tag "/images/plan_dummy.png", :size => "200x370", :class => "center"
.status
  %span.status-text
    = details_status items
  %span.status-icon
    = image_tag "/images/checkmark-green.png"

app/views/details/_weather-overview.html.haml
%h2 Weather
.section-content
  .weather-icon
    = image_tag "/images/Sunny.png", :size => "150x150", :class => "center"
  .weather-day
    Saturday
  .weather-icon
    = image_tag "/images/Slight_Drizzle.png", :size => "150x150", :class => "center"
  .weather-day
    Sunday
.status
  %span.status-text
    = details_status items
  %span.status-icon
    = image_tag "/images/checkmark-green.png"

app/views/details/add_item.html.haml
%em
  Actions to add, edit, and remove items still have to be implmented.

app/views/details/clothes.html.haml
.span-6
  .section
    = render :partial => "clothes-overview", :locals => { :items => @items }
.span-18.last
  = render :partial => "items"

app/views/details/pictures.html.haml
.span-6
  .section
    = render :partial => "pictures-overview", :locals => { :items => @items }
.span-18.last
  = render :partial => "items"

app/views/details/plan.html.haml
.span-6
  .section
    = render :partial => "plan-overview", :locals => { :items => @items }
.span-18.last
  = render :partial => "items"
  

app/views/details/weather.html.haml
.span-6
  .section
    = render :partial => "weather-overview", :locals => { :items => @items }
.span-18.last
  = render :partial => "items"

app/views/home/add_section.html.haml
.span-2
  &nbsp;
.span-20
  %em
    This page will allow to add more sections. It's out of the scope of the HCI
    class project, though.
.span-2.last

app/views/home/index.html.haml
.span-6
  .section.section-plan
    = render :partial => "details/plan-overview",
      :locals => { :items => @items1 }
.span-6
  .section.section-weather
    = render :partial => "details/weather-overview",
      :locals => { :items => @items2 }
.span-6
  .section.section-clothes
    = render :partial => "details/clothes-overview",
      :locals => { :items => @items3 }
.span-6.last
  .section.section-pictures
    = render :partial => "details/pictures-overview",
      :locals => { :items => @items4 }

:javascript
  $('.section-plan')
    .css('cursor', 'pointer')
    .click(
      function(){
        location.href = "/details/plan.html?id=#{@trip.id}";
      }
    )
    .hover(
      function(){
        $(this).css('background', '#FFFEE0');
      },
      function(){
        $(this).css('background', '');
      }
    );
  $('.section-weather')
    .css('cursor', 'pointer')
    .click(
      function(){
        location.href = "/details/weather.html?id=#{@trip.id}";
      }
    )
    .hover(
      function(){
        $(this).css('background', '#FFFEE0');
      },
      function(){
        $(this).css('background', '');
      }
    );
  $('.section-clothes')
    .css('cursor', 'pointer')
    .click(
      function(){
        location.href = "/details/clothes.html?id=#{@trip.id}";
      }
    )
    .hover(
      function(){
        $(this).css('background', '#FFFEE0');
      },
      function(){
        $(this).css('background', '');
      }
    );
  $('.section-pictures')
    .css('cursor', 'pointer')
    .click(
      function(){
        location.href = "/details/pictures.html?id=#{@trip.id}";
      }
    )
    .hover(
      function(){
        $(this).css('background', '#FFFEE0');
      },
      function(){
        $(this).css('background', '');
      }
    );

app/views/home/settings.html.haml
.span-2
  &nbsp;
.span-20
  %p
    %em
      This page will allow to control the settings like which items to add as
      auto-suggestions, where to take the pictures from for inspiration for
      activities, etc.
  %p
    = link_to "Auto-suggestion manager", :action => "suggestions"
  %p
    %em.help
      There will be a help text here.
.span-2.last

app/views/home/suggestions.html.haml
.span-2
  &nbsp;
.span-20
  - if @trip_id
    .overview-link
      = link_to "Back to overview", :controller => "home", :id => @trip_id
  .suggestion-manager-logo
    = image_tag "/images/suggested-logo-big.png"
  %h2 Auto-suggestion manager
  %p
    %em
      This page will allow to control the auto-suggestions, which items are
      added automatically on creation of a trip.
  %br{ :clear => "all" }
  %p
    %em Actual settings go here.
  %p
    %em.help
      There will be a help text here.
.span-2.last

app/views/layouts/_header.html.haml
.span-24.header
  .menu
    = link_to "All Trips", :controller => "trips"
    |
    = link_to "Settings", :controller => "home", :action => "settings"
    |
    = link_to "About", :controller => "about"
  %h2 I will travel...

app/views/layouts/_overview.html.haml
.span-16.overview
  .summary
    %span
      = @trip.location
    %span
      = trip_short_date @trip.from
    %span
      = trip_duration @trip
    %span.edit
      = link_to "Edit", :controller => "start"
.span-8.last.overview
  .total-status
    6/15 done

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title I will travel
    %link{:href => "/css/blueprint/screen.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/iwilltravel.css", :rel => "stylesheet", :type => "text/css"}/
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render :partial => "layouts/header"
      .span-24.spacer
        &nbsp;
      = yield
      .span-24.spacer
        &nbsp;
      .span-24.header
        HCI Class 2012

app/views/layouts/details.html.haml
!!!
%html
  %head
    %title I will travel
    %link{:href => "/css/blueprint/screen.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/iwilltravel.css", :rel => "stylesheet", :type => "text/css"}/
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render :partial => "layouts/header"
      = render :partial => "layouts/overview"
      .span-24.spacer
        &nbsp;
      = yield
      .span-24.spacer
        &nbsp;
      .span-24.footer
        HCI Class 2012

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title I will travel
    %link{:href => "/css/blueprint/screen.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/iwilltravel.css", :rel => "stylesheet", :type => "text/css"}/
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render :partial => "layouts/header"
      = render :partial => "layouts/overview"
      .span-24.spacer
        &nbsp;
      = yield
      .span-24.spacer
        &nbsp;
      .span-24.footer
        HCI Class 2012

app/views/layouts/start.html.haml
!!!
%html
  %head
    %title I will travel
    %link{:href => "/css/blueprint/screen.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/iwilltravel.css", :rel => "stylesheet", :type => "text/css"}/
    = javascript_include_tag "application"
    <link type="text/css" href="/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet" />
    <script type="text/javascript" src="/js/jquery-ui-1.8.21.custom.min.js"></script>
    = csrf_meta_tags
  %body
    .container
      = render :partial => "layouts/header"
      .span-24.spacer
        &nbsp;
      .story-frame
        = yield
      .span-24.spacer
        &nbsp;
      .span-24.footer
        HCI Class 2012

app/views/layouts/trips.html.haml
!!!
%html
  %head
    %title I will travel
    %link{:href => "/css/blueprint/screen.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/css/iwilltravel.css", :rel => "stylesheet", :type => "text/css"}/
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .span-24.header
        .menu
          = link_to "All Trips", :controller => "trips"
        %h2 I will travel...
      .story-frame
        = yield
      .span-24.header
        HCI Class 2012

app/views/start/enter.html.haml
%p.story
  I will travel.

= form_tag :action => "save" do
  %p
    = label_tag :location, "Where?"
    &nbsp;
    = text_field_tag :location, ""
    &nbsp;

  %p
    = label_tag :from, "From when?"
    &nbsp;
    = text_field_tag :from, "2012-06-30", :id => "datepicker1", :size => 10
    &nbsp;

  %p
    = label_tag :from, "Until when?"
    &nbsp;
    = text_field_tag :to, "2012-07-01", :size => 10, :id => "datepicker2"
    &nbsp;

  %p
    = hidden_field_tag :id, @trip.id
    = submit_tag "Proceed"

:javascript
  $(function() {
    $( "#datepicker1" ).datepicker({
      showAnim: "slideDown",
      dateFormat: "yy-mm-dd"
    });
  });
  $(function() {
    $( "#datepicker2" ).datepicker({
      showAnim: "slideDown",
      dateFormat: "yy-mm-dd"
    });
  });

app/views/start/from.html.haml
%p.story
  I will travel to #{@trip.location} on #{trip_date @trip.from}.

= form_tag :action => "to" do
  = label_tag :from, "Until when?"
  &nbsp;
  = text_field_tag :to, "2012-07-01", :size => 10, :id => "datepicker"
  &nbsp;
  = hidden_field_tag :id, @trip.id
  = submit_tag "Proceed"

:javascript
  $(function() {
    $( "#datepicker" ).datepicker({
      showAnim: "slideDown",
      dateFormat: "yy-mm-dd"
    });
  });

app/views/start/index.html.haml
%p.story
  I will travel.

= form_tag :action => "location" do
  = label_tag :location, "Where?"
  &nbsp;
  = text_field_tag :location, ""
  &nbsp;
  = hidden_field_tag :id, @trip.id
  = submit_tag "Proceed"

app/views/start/location.html.haml
%p.story
  I will travel to #{@trip.location}.

= form_tag :action => "from" do
  = label_tag :from, "From when?"
  &nbsp;
  = text_field_tag :from, "2012-06-30", :id => "datepicker", :size => 10
  &nbsp;
  = hidden_field_tag :id, @trip.id
  = submit_tag "Proceed"

:javascript
  $(function() {
    $( "#datepicker" ).datepicker({
      showAnim: "slideDown",
      dateFormat: "yy-mm-dd"
    });
  });

app/views/start/to.html.haml
%p.story
  I will travel to #{@trip.location} for #{trip_duration @trip}
  from #{trip_date @trip.from}, to #{trip_date @trip.to}.

= link_to "Plan my trip", :controller => "home", :action => "index",
  :id => @trip.id 

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.haml
%p
  = link_to "Plan new trip", :controller => "start"

%p
  = link_to "Plan new trip", :controller => "start", :action => "enter"
  (Alternative startup wizard for comparative UI testing)

%h2 My trips

%ul
- @trips.each do |trip|
  %li
    = link_to trip_title(trip), :controller => "home", :id => trip.id
    %span.destroy-link
      = link_to "Delete", trip_path(trip), :method => :delete

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>